[DEV-10216] Update RestSharp version and resolve code changes.
HelloFax/hellosign-dotnet-sdk pull request #116
Opened 2022-04-19 14:17 UTC by collinWheeler

2022-04-19 21:44 UTC, d-thiele commented
I would love to see this get some attention and hopefully merged into a new release, assuming it passes an QA testing. Thanks @collinWheeler!!!

2022-05-03 19:29 UTC, erkkinen requested changes

2022-05-03 19:29 UTC, erkkinen commented on src/HelloSign/HelloSign.cs
> +        public Client(string apiKey, string apiHost) : this()
We should make this `apiHost` optional allowing it to default to the original `api.hellosign.com`

2022-05-03 19:29 UTC, erkkinen commented on src/HelloSign/Models/ApiApp.cs
> +        public string getDomain()
I think we should probably just override the default property setters like

2022-05-03 19:29 UTC, erkkinen commented on src/HelloSign/HelloSign.cs
> +        private void HandleErrors(RestResponse response)
Why are we changing this from the interface?

2022-05-03 19:29 UTC, erkkinen commented on HelloSign.sln
> +		{99D13956-F763-4F4F-96B9-35B8C91AA836}.Debug|Any CPU.ActiveCfg = Release|Any CPU
Why are we setting these to Release instead?

2022-05-03 19:29 UTC, erkkinen commented on src/HelloSign/HelloSign.cs
> +            client = new RestClient(GetFullHostname(apiHost));
Do not create a new RestClient here. We are calling the default constructor with the : this() call, which is setting the user agent to the proper SDK version, which we want. overriding it here will get rid of that. Instead if `apiHost` is set update the url

2022-05-03 19:29 UTC, erkkinen commented on src/HelloSign/HelloSign.cs
> +        /// <param name="apiHost">Your HelloSign account API key.</param>
Comment is incorrect

2022-05-03 19:29 UTC, erkkinen commented on src/HelloSign/HelloSign.cs
> +            // = new Uri(String.Format("https://api.{0}/v3", domain));
Remove commented code

2022-05-03 19:29 UTC, erkkinen commented on src/HelloSign/HelloSign.cs
> +            client = new RestClient(new Uri(String.Format("https://api.{0}/v3", domain)));
Hmm, I see the issue now with the fact RestSharp removed the ability to set the BaseURL. I would abstract a method to create and set the RestClient, so we can ensure we always set the user agent as this here like the constructor above drops the user-agent.

2022-05-03 19:29 UTC, erkkinen commented on src/HelloSign/HelloSign.cs
> +            var request = new RestRequest("account", Method.Post).AddQueryParameter("callback_url", callbackUrl.ToString());
This should be AddParameter, not AddQueryParameter I think

2022-05-03 19:29 UTC, erkkinen commented on src/HelloSign/HelloSign.cs
> -                request.AddParameter("page", page);
Why the null coalescence? We already have a null check directly above

2022-05-03 19:29 UTC, erkkinen commented on src/HelloSign/HelloSign.cs
> -                request.AddParameter("page_size", pageSize);
Why the null coalescence? We already have a null check directly above

2022-05-03 19:29 UTC, erkkinen commented on src/HelloSign/HelloSign.cs
> +                request.AddParameter("page", page ?? 0);
Why the null coalescence? We already have a null check directly above

2022-05-03 19:29 UTC, erkkinen commented on src/HelloSign/HelloSign.cs
> +                request.AddParameter("page_size", pageSize ?? 0);
Why the null coalescence? We already have a null check directly above

2022-05-03 19:29 UTC, erkkinen commented on src/HelloSign/HelloSign.cs
> +                request.AddParameter("page", page ?? 0);
Why the null coalescence? We already have a null check directly above

2022-05-03 19:29 UTC, erkkinen commented on src/HelloSign/HelloSign.cs
> +                request.AddParameter("page_size", pageSize ?? 0);
Why the null coalescence? We already have a null check directly above

2022-05-03 19:29 UTC, erkkinen commented on src/HelloSign/Models/Event.cs
> -        public Account Account { get; set; }
Why are we removing this?

2022-05-03 19:29 UTC, erkkinen commented on src/HelloSign/HelloSign.cs
> -            request.AddParameter("domain", app.Domain);
Should we not add the ability to send domains? Or we can even always have it as domains instead of domain from now on, and just wrap the domain in an array/list

2022-05-04 01:25 UTC, collinWheeler commented on src/HelloSign/HelloSign.cs
> +            client = new RestClient(GetFullHostname(apiHost));
The RestClient doesn't allow the URL to be changed after initialization, but this can be achieved in a different way:

public Client(string apiHost = null)
{
   ...
   client = new RestClient(GetFullHostname(apiHost ?? defaultHost));
   client.AddDefaultHeader("User-Agent", "hellosign-dotnet-sdk/" + Version);
}
public Client(string apiKey, string apiHost = null) : this(apiHost)
{
   this.UseApiKeyAuthentication(apiKey);
}

2022-05-04 01:51 UTC, collinWheeler commented on src/HelloSign/HelloSign.cs
> -                request.AddParameter("page", page);
The RestSharp request doesn't allow a nullable object for this function, even if protected by an if statement. However, it looks like it does allow the `.Value` member. That could be a potential fix.

2022-05-04 14:47 UTC, collinWheeler commented on src/HelloSign/Models/Event.cs
> -        public Account Account { get; set; }
The event response object doesn't include an Account, only an Account_Id in its metadata. Since all we do with the Event is parse it into an object, keeping this Account member is inaccurate.

2022-05-06 19:24 UTC, erkkinen approved these changes
LGTM

2022-05-31 10:55 UTC, rameshv21 commented on src/HelloSign/HelloSign.csproj
> +    <PackageReference Include="RestSharp" Version="107.3.0" />
Hi 
When I am trying to update this package it is showing below.
![image](https://user-images.githubusercontent.com/102604573/171157934-d4a5aa8f-8923-47c6-aca6-0b4bc4294b30.png)
![image](https://user-images.githubusercontent.com/102604573/171157934-d4a5aa8f-8923-47c6-aca6-0b4bc4294b30.png)

2022-05-31 10:55 UTC, rameshv21 commented on src/HelloSign/HelloSign.csproj
> +    <PackageReference Include="RestSharp" Version="107.3.0" />
Hi 
When I am trying to update this package it is showing below.
![image](https://user-images.githubusercontent.com/102604573/171157934-d4a5aa8f-8923-47c6-aca6-0b4bc4294b30.png)
![image](https://user-images.githubusercontent.com/102604573/171157934-d4a5aa8f-8923-47c6-aca6-0b4bc4294b30.png)

2022-06-02 18:06 UTC, collinWheeler commented on src/HelloSign/HelloSign.csproj
> +    <PackageReference Include="RestSharp" Version="107.3.0" />
Hello, is the issue that the RestSharp update is freezing?

2022-06-17 22:15 UTC, d-thiele commented
@erkkinen and @collinWheeler - This seems to be ready to merge, right? What else is needed before that can be done and a new release be published with these changes?

2022-07-14 14:58 UTC, gdblack commented
Any movement or ETA for this getting merged in? There is a security vulnerability with lower versions of RestSharp: https://www.cve.org/CVERecord?id=CVE-2021-27293
We require Hellosign SDK for a major portion of our application and would like to see this happen if possible.

2022-07-20 23:50 UTC, merged