Add SMS verification parameter
HelloFax/hellosign-dotnet-sdk pull request #98
Opened 2021-01-20 23:26 UTC by durgeshpatel-hs

- Adds SMS verification parameter `sms_phone_number` in `Signer` model
- Parameter is supported in the following API endpoints:
```
signature_request/send
signature_request/send_with_template
signature_request/create_embedded
signature_request/create_embedded_with_template
```

2021-01-21 00:23 UTC, BHSPitMonkey requested changes

2021-01-21 00:23 UTC, BHSPitMonkey commented on src/HelloSign/Models/Signer.cs
> +        public Signer(string emailAddress, string name, int? order = null, string pin = null, string smsPhoneNumber = null, string role = null)
Changing the parameter order here might break someone's implementation (if they happen to be creating `Signer` objects / pushing them into `Signers` directly, instead of using the convenience method). I think we may want to just add `smsPhoneNumber` at the end, even if it looks a little off as a result

2021-01-21 01:49 UTC, durgeshpatel-hs commented on src/HelloSign/Models/Signer.cs
> +        public Signer(string emailAddress, string name, int? order = null, string pin = null, string smsPhoneNumber = null, string role = null)
Done

2021-01-22 00:12 UTC, BHSPitMonkey approved these changes

2021-02-02 19:09 UTC, merged